Rails.application.routes.draw do
  
  # form for creating a new reference
  get 'references/new', to: 'references#new', as: 'new_reference'
  
  # editing an existing reference object
  get 'references/:id/edit', to: 'references#edit', as: 'edit_reference'

  # delete a specific object
  delete 'references/:id', to: 'references#destroy'

  # an individual Reference object
  get 'references/:id', to: 'references#show', as: 'reference'

  # all Reference objects
  get 'references', to: 'references#index', as: 'references'

  # after form generated by new is filled out user comes to this page to create the actual object
  post 'references', to: 'references#create'
  
  # after form generated by edit is filled out user comes to this page to update the actual object
  patch 'references/:id', to: 'references#update'

  root 'references#index'

end
