Rails.application.routes.draw do
  
  # form for creating a new reference
  get 'references/new', to: 'references#new', as: 'new_reference'

  # an individual Reference object
  get 'references/:id', to: 'references#show', as: 'reference'

  # all Reference objects
  get 'references', to: 'references#index', as: 'references'

  # after form generated by new is filled out user comes to this page to create the actual object
  post 'references', to: 'references#create'
  
  root 'references#index'

end
